### PR TITLE
PR

### PR DESCRIPTION
**Pull request by santosh653**
Adding power support ppc64le

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.
The Python Versions=pypy are not available for download and hence excluded from the travis.yml & the build is enabled for other versions of python.
Build is enabled for both arch: ppc64le/amd64.

### CODE REVIEW

**Comment by santosh653** [comment]
Can this PR be accepted?

**Comment by santosh653** [comment]
If all the tests are successful, Can you please consider this PR to process further?

**Comment by santosh653** [comment]
@audreyfeldroy If all the checks are successful, Can we have this PR processed further? It's been open from quite a few days now.

**Comment by santosh653** [comment]
@audreyfeldroy If all the tests are successful, Can we have this PR processed further?

**Comment by santosh653** [comment]
Can you please check this PR & approve?

**Comment by santosh653** [comment]
In case there are no further checks to be verified, Can we have this PR approved? It is open from quite sometime now.

**Comment by santosh653** [comment]
Can you Please check & approve? It's been open from very long time.,

**Comment by santosh653** [comment]
@audreyfeldroy Herewith Checking if you have any further questions on this.

Thank you!!

**Comment by santosh653** [comment]
A gentle nudge, Checking if you have any questions on this PR!!

**Comment by santosh653** [comment]
A gentle reminder to Let us know if you have any further queries on this PR?

**Comment by santosh653** [comment]
Checking herewith if there are any further queries here?

**Comment by santosh653** [comment]
@audreyfeldroy Are there any queries open on this PR?

**Comment by pombredanne** [comment]
@santosh653 We are rebooting the project and we are no longer using Travis since they changed their support for FOSS projects. So I can only close this. It would be awesome to get this to run on GitHub actions though. Thank you in all cases.

**Pull request closed without merging**
